name: Tests

on:
  pull_request:
      branches:
        - master
        - dev
  push:
    branches:
      - master
      - dev
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt -r requirements.txt
    - name: Pylint
      run: |
        pylint anyway tests main.py
  Black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade black
    - name: black formatting
      run: |
        black anyway/**/*.py -l 100 --verbose --check
    - name: Super-Linter
      uses: github/super-linter@v3.14.0
